# Generated by Django 6.0.7 on 2026-08-24 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis_go_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='mission',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='bbox',
            field=models.ImageField(blank=True, null=True, upload_to='bboxes/'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Only lowercase letters, numbers and underscore, between 3 and 20 characters.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, numbers and underscore, between 3 and 20 characters.', regex='^[a-z0-9_]{3,20}$')], verbose_name='username'),
        ),
    ]
