# Generated by Django 6.0.7 on 2026-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis_go_app', '0002_alter_goal_x_alter_goal_y_alter_goal_z_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='state',
            field=models.CharField(choices=[('REACHED', 'Reached'), ('NOT_REACHED', 'Not Reached'), ('REJECTED', 'Rejected')], default='REACHED', max_length=11),
        ),
        migrations.AlterField(
            model_name='mission',
            name='time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
